# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-22.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v4

      - name: Install curl
        run: sudo apt-get install -y libcurl4-openssl-dev

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'
          use-public-rspm: true
          extra-repositories: https://iqnca.intiquan.com/rrepo

      - name: Install IQnca # pak fails to install it, but install.packages can
        run: install.packages('IQnca')
        shell: Rscript {0}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
